# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from trackshift.manifest import manifest_pb2 as trackshift_dot_manifest_dot_manifest__pb2


class ManifestIngestServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadManifest = channel.unary_unary(
                '/trackshift.manifest.ManifestIngestService/UploadManifest',
                request_serializer=trackshift_dot_manifest_dot_manifest__pb2.UploadManifestRequest.SerializeToString,
                response_deserializer=trackshift_dot_manifest_dot_manifest__pb2.UploadManifestResponse.FromString,
                _registered_method=True)
        self.UploadChunk = channel.stream_unary(
                '/trackshift.manifest.ManifestIngestService/UploadChunk',
                request_serializer=trackshift_dot_manifest_dot_manifest__pb2.UploadChunkRequest.SerializeToString,
                response_deserializer=trackshift_dot_manifest_dot_manifest__pb2.UploadChunkResponse.FromString,
                _registered_method=True)


class ManifestIngestServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadManifest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadChunk(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManifestIngestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadManifest,
                    request_deserializer=trackshift_dot_manifest_dot_manifest__pb2.UploadManifestRequest.FromString,
                    response_serializer=trackshift_dot_manifest_dot_manifest__pb2.UploadManifestResponse.SerializeToString,
            ),
            'UploadChunk': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadChunk,
                    request_deserializer=trackshift_dot_manifest_dot_manifest__pb2.UploadChunkRequest.FromString,
                    response_serializer=trackshift_dot_manifest_dot_manifest__pb2.UploadChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trackshift.manifest.ManifestIngestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trackshift.manifest.ManifestIngestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ManifestIngestService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trackshift.manifest.ManifestIngestService/UploadManifest',
            trackshift_dot_manifest_dot_manifest__pb2.UploadManifestRequest.SerializeToString,
            trackshift_dot_manifest_dot_manifest__pb2.UploadManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadChunk(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/trackshift.manifest.ManifestIngestService/UploadChunk',
            trackshift_dot_manifest_dot_manifest__pb2.UploadChunkRequest.SerializeToString,
            trackshift_dot_manifest_dot_manifest__pb2.UploadChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
