# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trackshift/decisionlog/decision_log.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'trackshift/decisionlog/decision_log.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from trackshift.common import common_pb2 as trackshift_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)trackshift/decisionlog/decision_log.proto\x12\x16trackshift.decisionlog\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1etrackshift/common/common.proto\"U\n\x0cPathDecision\x12\x17\n\x07path_id\x18\x01 \x01(\tR\x06pathId\x12\x14\n\x05score\x18\x02 \x01(\x01R\x05score\x12\x16\n\x06reason\x18\x03 \x01(\tR\x06reason\"\x81\x01\n\x0bPolicyEvent\x12\x1b\n\tpolicy_id\x18\x01 \x01(\tR\x08policyId\x12=\n\x08\x64\x65\x63ision\x18\x02 \x01(\x0e\x32!.trackshift.common.PolicyDecisionR\x08\x64\x65\x63ision\x12\x16\n\x06\x64\x65tail\x18\x03 \x01(\tR\x06\x64\x65tail\"{\n\x08\x44lpEvent\x12\x1a\n\x08provider\x18\x01 \x01(\tR\x08provider\x12\x18\n\x07verdict\x18\x02 \x01(\tR\x07verdict\x12\x39\n\ndecided_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tdecidedAt\"F\n\x06Metric\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n\x05value\x18\x02 \x01(\x01R\x05value\x12\x12\n\x04unit\x18\x03 \x01(\tR\x04unit\"\x8a\x03\n\x0b\x44\x65\x63isionLog\x12\x15\n\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x17\n\x07\x65\x64ge_id\x18\x02 \x01(\tR\x06\x65\x64geId\x12K\n\x0epath_decisions\x18\x03 \x03(\x0b\x32$.trackshift.decisionlog.PathDecisionR\rpathDecisions\x12H\n\rpolicy_events\x18\x04 \x03(\x0b\x32#.trackshift.decisionlog.PolicyEventR\x0cpolicyEvents\x12?\n\ndlp_events\x18\x05 \x03(\x0b\x32 .trackshift.decisionlog.DlpEventR\tdlpEvents\x12\x38\n\x07metrics\x18\x06 \x03(\x0b\x32\x1e.trackshift.decisionlog.MetricR\x07metrics\x12\x39\n\ncreated_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\tcreatedAtB=Z;github.com/trackshift/platform/proto/trackshift/decisionlogb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trackshift.decisionlog.decision_log_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/trackshift/platform/proto/trackshift/decisionlog'
  _globals['_PATHDECISION']._serialized_start=134
  _globals['_PATHDECISION']._serialized_end=219
  _globals['_POLICYEVENT']._serialized_start=222
  _globals['_POLICYEVENT']._serialized_end=351
  _globals['_DLPEVENT']._serialized_start=353
  _globals['_DLPEVENT']._serialized_end=476
  _globals['_METRIC']._serialized_start=478
  _globals['_METRIC']._serialized_end=548
  _globals['_DECISIONLOG']._serialized_start=551
  _globals['_DECISIONLOG']._serialized_end=945
# @@protoc_insertion_point(module_scope)
