# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from trackshift.jobs import job_spec_pb2 as trackshift_dot_jobs_dot_job__spec__pb2


class JobServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateJob = channel.unary_unary(
                '/trackshift.jobs.JobService/CreateJob',
                request_serializer=trackshift_dot_jobs_dot_job__spec__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=trackshift_dot_jobs_dot_job__spec__pb2.CreateJobResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/trackshift.jobs.JobService/GetJob',
                request_serializer=trackshift_dot_jobs_dot_job__spec__pb2.GetJobRequest.SerializeToString,
                response_deserializer=trackshift_dot_jobs_dot_job__spec__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/trackshift.jobs.JobService/ListJobs',
                request_serializer=trackshift_dot_jobs_dot_job__spec__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=trackshift_dot_jobs_dot_job__spec__pb2.ListJobsResponse.FromString,
                _registered_method=True)


class JobServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JobServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=trackshift_dot_jobs_dot_job__spec__pb2.CreateJobRequest.FromString,
                    response_serializer=trackshift_dot_jobs_dot_job__spec__pb2.CreateJobResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=trackshift_dot_jobs_dot_job__spec__pb2.GetJobRequest.FromString,
                    response_serializer=trackshift_dot_jobs_dot_job__spec__pb2.GetJobResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=trackshift_dot_jobs_dot_job__spec__pb2.ListJobsRequest.FromString,
                    response_serializer=trackshift_dot_jobs_dot_job__spec__pb2.ListJobsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'trackshift.jobs.JobService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('trackshift.jobs.JobService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class JobService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trackshift.jobs.JobService/CreateJob',
            trackshift_dot_jobs_dot_job__spec__pb2.CreateJobRequest.SerializeToString,
            trackshift_dot_jobs_dot_job__spec__pb2.CreateJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trackshift.jobs.JobService/GetJob',
            trackshift_dot_jobs_dot_job__spec__pb2.GetJobRequest.SerializeToString,
            trackshift_dot_jobs_dot_job__spec__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/trackshift.jobs.JobService/ListJobs',
            trackshift_dot_jobs_dot_job__spec__pb2.ListJobsRequest.SerializeToString,
            trackshift_dot_jobs_dot_job__spec__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
