# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trackshift/chunkref/chunk_ref.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'trackshift/chunkref/chunk_ref.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#trackshift/chunkref/chunk_ref.proto\x12\x13trackshift.chunkref\"\xcc\x01\n\x08\x43hunkRef\x12\x14\n\x05index\x18\x01 \x01(\rR\x05index\x12\x1d\n\nchunk_hash\x18\x02 \x01(\x0cR\tchunkHash\x12\x16\n\x06offset\x18\x03 \x01(\x04R\x06offset\x12\x16\n\x06length\x18\x04 \x01(\rR\x06length\x12!\n\x0cstorage_hint\x18\x05 \x01(\tR\x0bstorageHint\x12\x17\n\x07path_id\x18\x06 \x01(\tR\x06pathId\x12\x1f\n\x0bmerkle_path\x18\x07 \x03(\x0cR\nmerklePathB:Z8github.com/trackshift/platform/proto/trackshift/chunkrefb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trackshift.chunkref.chunk_ref_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/trackshift/platform/proto/trackshift/chunkref'
  _globals['_CHUNKREF']._serialized_start=61
  _globals['_CHUNKREF']._serialized_end=265
# @@protoc_insertion_point(module_scope)
