# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: trackshift/intent/intent.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'trackshift/intent/intent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from trackshift.common import common_pb2 as trackshift_dot_common_dot_common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etrackshift/intent/intent.proto\x12\x11trackshift.intent\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1etrackshift/common/common.proto\"9\n\x0fIntentAttribute\x12\x10\n\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n\x05value\x18\x02 \x01(\tR\x05value\"\x9a\x03\n\x06Intent\x12\x34\n\x07urgency\x18\x01 \x01(\x0e\x32\x1a.trackshift.common.UrgencyR\x07urgency\x12\x36\n\x08\x64\x65\x61\x64line\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.TimestampR\x08\x64\x65\x61\x64line\x12!\n\x0c\x63ost_ceiling\x18\x03 \x01(\x01R\x0b\x63ostCeiling\x12P\n\x11reliability_level\x18\x04 \x01(\x0e\x32#.trackshift.common.ReliabilityLevelR\x10reliabilityLevel\x12\x44\n\x0bsensitivity\x18\x05 \x01(\x0e\x32\".trackshift.common.DataSensitivityR\x0bsensitivity\x12#\n\rregion_policy\x18\x06 \x01(\tR\x0cregionPolicy\x12\x42\n\nattributes\x18\x07 \x03(\x0b\x32\".trackshift.intent.IntentAttributeR\nattributes\"d\n\x0fPathRequirement\x12\x17\n\x07path_id\x18\x01 \x01(\tR\x06pathId\x12 \n\x0b\x64\x65scription\x18\x02 \x01(\tR\x0b\x64\x65scription\x12\x16\n\x06weight\x18\x03 \x01(\x01R\x06weight\"\xa7\x01\n\x08\x46ileSpec\x12\x10\n\x03uri\x18\x01 \x01(\tR\x03uri\x12\x1a\n\x08\x63hecksum\x18\x02 \x01(\tR\x08\x63hecksum\x12+\n\x11redundancy_target\x18\x03 \x01(\tR\x10redundancyTarget\x12\x1d\n\nchunk_size\x18\x04 \x01(\rR\tchunkSize\x12!\n\x0cpqc_required\x18\x05 \x01(\x08R\x0bpqcRequiredB8Z6github.com/trackshift/platform/proto/trackshift/intentb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'trackshift.intent.intent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/trackshift/platform/proto/trackshift/intent'
  _globals['_INTENTATTRIBUTE']._serialized_start=118
  _globals['_INTENTATTRIBUTE']._serialized_end=175
  _globals['_INTENT']._serialized_start=178
  _globals['_INTENT']._serialized_end=588
  _globals['_PATHREQUIREMENT']._serialized_start=590
  _globals['_PATHREQUIREMENT']._serialized_end=690
  _globals['_FILESPEC']._serialized_start=693
  _globals['_FILESPEC']._serialized_end=860
# @@protoc_insertion_point(module_scope)
